function [fitresult, gof] = Arm_Lfit(Threshold_arr, arm_dac_arr,leg,x_label,y_label,VFAT3_NUMBER,Pre_Gain,Peaking_time)
%CREATEFIT2(THRESHOLD_ARR,ARM_DAC_ARR)
%  Create a fit.
%
%  Data for 'Arm_Lfit' fit:
%      X Input : Threshold_arr
%      Y Output: arm_dac_arr
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 29-May-2018 13:50:49


%% Fit: 'Arm_Lfit'.
[xData, yData] = prepareCurveData( Threshold_arr, arm_dac_arr );

% Set up fittype and options.
ft = fittype( 'poly1' );
opts = fitoptions( 'Method', 'LinearLeastSquares' );
%opts.Normalize = 'on';
opts.Robust = 'Bisquare';

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );
%ystep = fitresult(xData(2) ) - fitresult(xData(1)) 
%xstep = xData(2) - xData(1)
% Plot fit with data.
figure( 'Name', 'ArmLfit' );
h = plot( fitresult, xData, yData );
legend( h, leg, 'ArmLfit', 'Location', 'SouthEast' );%'ArmDac vs. Threshold'
% Label axes
xlabel(x_label); %Threshold(fC)
ylabel(y_label);% ArmDac
grid on

str0 = ['',VFAT3_NUMBER];
str1 = ['',num2str(Pre_Gain),',',num2str(Peaking_time)];
str2 = [ 'Y = p1*X + p2 (p1:',num2str(round(fitresult.p1,2)),',','p2:',num2str(round(fitresult.p2,2)),')'];
x0=min(xData)+ .1;y0=max(yData)- 1;
x1=x0 ;y1=y0 - 2;
x2=x0; y2=y1 - 2;
text(x0,y0,str0);
text(x1,y1,str1);
text(x2,y2,str2);


