function [fitresult, gof] = createFit1(x, y)
%CREATEFIT1(X,Y)
%  Create a fit.
%
%  Data for 'erf_fit' fit:
%      X Input : x
%      Y Output: y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 05-May-2018 10:00:21


%% Fit: 'erf_fit'.
[xData, yData] = prepareCurveData( x, y );

% Set up fittype and options.
ft = fittype( '0.5 * erf( (x-a)/(sqrt(2)*b) ) + 0.5', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Algorithm = 'Levenberg-Marquardt';
opts.Display = 'Off';
opts.StartPoint = [2 .5];%[2 .2];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% % % Plot fit with data.
%  figure( 'Name', 'erf_fit' );
% h = plot( fitresult, xData, yData );
% legend( h, 'y vs. x', 'erf_fit', 'Location', 'NorthEast' );
%  % Label axes
% legend off
%  xlabel charge
%  ylabel occupancy
%  grid on


