function [fitresult, gof] = LinearFit_No_Plot(x, y)
%CREATEFIT2(CHARGE,CAL_DAC)
%  Create a fit.
%
%  Data for 'LinearFit' fit:
%      X Input : charge
%      Y Output: cal_dac
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 10-May-2018 18:08:14


%% Fit: 'LinearFit'.
[xData, yData] = prepareCurveData( x, y );

% Set up fittype and options.
ft = fittype( 'poly1' );
opts = fitoptions( 'Method', 'LinearLeastSquares' );
opts.Robust = 'Bisquare';

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );
end