function [fitresult, gof] = Polyfit_trimdac(x_data, y_data)
%CREATEFIT2(X_DATA,Y_DATA)
%  Create a fit.
%
%  Data for 'polyfit' fit:
%      X Input : x_data
%      Y Output: y_data
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 01-Jul-2018 00:19:53


%% Fit: 'polyfit'.
[xData, yData] = prepareCurveData( x_data, y_data );

% Set up fittype and options.
ft = 'splineinterp';

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% Plot fit with data.
figure( 'Name', 'polyfit' );
h = plot( fitresult, xData, yData );
legend( h, 'y_data vs. x_data', 'polyfit', 'Location', 'NorthEast' );
% Label axes
xlabel x_data
ylabel y_data
grid on


