function [fitresult, gof] = Trim_fit(xx, yy)
%CREATEFIT2(XX,YY)
%  Create a fit.
%
%  Data for 'Trim_fit' fit:
%      X Input : xx
%      Y Output: yy
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 07-May-2018 20:32:03


%% Fit: 'Trim_fit'
[xData, yData] = prepareCurveData( xx, yy );

% Set up fittype and options
ft = fittype( 'poly1' );
opts = fitoptions( 'Method', 'LinearLeastSquares' );
opts.Robust = 'LAR';

% Fit model to data
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data
% figure( 'Name', 'Trim_fit' );
% h = plot( fitresult, xData, yData );
% legend( h, 'Trim fit plot', 'TrimFit', 'Location', 'SouthEast' );
% Label axes


