function [fitresult, gof] = LinearFit(x, y)
%CREATEFIT2(X,I_PRE)
%  Create a fit.
%
%  Data for 'Linear fit' fit:
%      X Input : x
%      Y Output: I_PRE
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 16-Aug-2018 10:23:35


%% Fit: 'Linear fit'.
[xData, yData] = prepareCurveData( x, y );

% Set up fittype and options.
ft = fittype( 'poly1' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% Plot fit with data.
figure( 'Name', 'Linear fit' );
h = plot( fitresult, xData, yData );
legend( h, 'y vs. x', 'Linear fit', 'Location', 'NorthEast' );
% Label axes
xlabel x
ylabel y
grid on


